#!/bin/bash

# set the minimum and maximum frequencies for the modes
fmin=0.1
fmax=3.0

# set the range of structural degrees
smin=0
smax=20

# rotation on == 1, off == 0
rot=1

# ellipticity on == 1, off = 0
ell=1

# set the name for the matrix file
file="matrix.bin"

../../coupling/bin/mode_list << !
$fmin
$fmax
!

../../coupling/bin/mdcpl << !
$smin
$smax
$rot
$ell
$file
!
