#!/bin/bash

export OMP_NUM_THREADS=3

# set minimum and maximum frequency for the calculations (in mHz)
fmin=0.5
fmax=1.0

# time step (seconds)
tstep=20

# time length (hours)
tend=256

# frequency step (mHz)
fstep=0.2

# target block width (mHz)
fblock=0.05

# start and end times for Cosine Bell window (hours)
wstart=0
wend=60
soltol=0.000001
qex=4;

../build/bin/test << !
$fmin
$fmax
$tstep
$tend
$fstep
$fblock
$wstart
$wend
$soltol
$qex
!

