#!/bin/bash

export OMP_NUM_THREADS=16

# set minimum and maximum frequency for the calculations (in mHz)
fmin=0.1
fmax=2.5

# time step (seconds)
tstep=20

# time length (hours)
tend=256

# frequency step (mHz)
fstep=0.05

# target block width (mHz)
fblock=0.05

# start and end times for Cosine Bell window (hours)
wstart=0
wend=256
soltol=0.000001
qex=4;

../build/bin/testRK << !
$fmin
$fmax
$tstep
$tend
$fstep
$fblock
$wstart
$wend
$soltol
$qex
!

