#!/bin/bash
# set minimum and maximum frequency for the calculations (in mHz)
fmin=0.1
fmax=3.5

# time step (seconds)
tstep=20

# time length (hours)
tend=512

# frequency step (mHz)
fstep=0.05

# target block width (mHz)
fblock=0.05

# start and end times for Cosine Bell window (hours)
wstart=0
wend=512
soltol=0.000001

../build/bin/test << !
$fmin
$fmax
$tstep
$tend
$fstep
$fblock
$wstart
$wend
$soltol
!