#!/bin/bash

rm out.time

TIMEFORMAT=%R
for i in {1..32}
do
    export OMP_NUM_THREADS=$i
    # echo "Hello $i"
    # echo "$i;" >> out.time
    exec 3>&1 4>&2
    myt=$( { time run_test 1>&3 2>&4; } 2>&1)
    exec 3>&- 4>&-
    # myt= $( (time run_test 1 2 > test.out) );   
    echo "$i;$myt" >>out.time
done